# Use stable Flutter image (includes Android SDK & Java)
FROM ghcr.io/cirruslabs/flutter:stable

# Set working directory
WORKDIR /app

# Install necessary Linux tools for compiling plugins
RUN sudo apt-get update && sudo apt-get install -y \
    clang \
    cmake \
    ninja-build \
    pkg-config \
    libgtk-3-dev

# Accept Android Licenses
RUN yes | flutter doctor --android-licenses

# Copy pubspec files first to cache dependencies
COPY pubspec.yaml pubspec.lock ./
RUN flutter pub get

# Expose ports
EXPOSE 8080 
